- name: Configure an nginx website on workstation
  hosts: workstation
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Copy website images to workstation
      ansible.builtin.copy:
        src: image/
        dest: /usr/share/nginx/html/image/
        owner: root
        group: root
        mode: "0755"

    - name: Create website index page
      ansible.builtin.template:
        src: website.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Open http port in firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
