---
- name: Create custom resources in controller
  hosts: localhost

  tasks:

    - name: Create Student Git credential
      ansible.controller.credential:
        name: Student Git
        description: Student Git credential
        organization: Default
        controller_host: https://controller.lab.example.com
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        state: present
        credential_type: Source Control
        inputs:
          username: student
          password: StuD3nt123!@

    - name: Create Run Practice project
      ansible.controller.project:
        name: Run Practice
        description: Single playbook practice project
        organization: Default
        controller_host: https://controller.lab.example.com
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        state: present
        scm_type: git
        scm_url: https://git.lab.example.com/student/playbooks.git
        scm_clean: true
        scm_update_on_launch: true



  
