---
- name: Create custom resources in controller
  hosts: localhost

  tasks:

    - name: Create Student Git credential
      ansible.controller.credential:
        name: Student Git
        description: Student Git credential
        organization: Default
        controller_host: https://controller.lab.example.com
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        state: present
        credential_type: Source Control
        inputs:
          username: student
          Password: StuD3nt123!@

  
